name: spherical-eqs
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.12.*
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - black
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - pandas
  - geopandas
  - xarray
  - netcdf4
  - numba
  - pygmt
  - gmt==6.4.*
  - pyproj
  - rich
  - ipywidgets
  # Fatiando
  - boule
  - pooch
  - verde
  - harmonica
  - choclo
  - bordado
